modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Hydroceder/espoints/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL=""
credits="Hydroceder"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tetrachordlib"
    mandatory=true
    versionRange="[${tetrachord_version}]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="espetro"
    mandatory=true
    versionRange="[${espetro_version}]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="pingwheel"
    mandatory=true
    versionRange="[${pingwheel_version}]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="esradial"
    mandatory=true
    versionRange="[${esradial_version}]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="apricityui"
    mandatory=true
    versionRange="[${apricityui_version}]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="oelib"
    mandatory=true
    versionRange="[${oelib_version},)"
    ordering="AFTER"
    side="BOTH"
